install.packages(c("pacman",
                   "tidyverse",
              	   "testthat",
              	   "xml2",
              	   "rvest",
              	   "tictoc",
              	   "furrr",
                   "devtools",
                   "tidyjson"
              	   )) 
